### ISSUE TITLE
Add a way to say how many sites we have blocked from selling your data, etc

### ISSUE THREAD

**Issue by dknopf** [privacy-tech-lab/optmeowt-browser-extension#102]
It could definitely be nice to say "7,900 sites blocked from selling your data!" or something like that somewhere, just so that the user knows the extension is doing something. Right now it's a bit hard to tell if the extension is having any effect so something like this could potentially be reassuring. Maybe this could be in the popup somewhere.

**Comment by SebastianZimmeck** [comment]
Excellent idea! For example, in Brave I am seeing the below. Maybe, we can add something similar.

<img width="584" alt="Screen Shot 2020-10-19 at 8 11 49 PM" src="https://user-images.githubusercontent.com/11034003/96524898-7b90d780-1247-11eb-86d4-2222199fb88b.png">

**Comment by SebastianZimmeck** [comment]
As we discussed today, the idea is to implement a tracker of how many unique domains have received a Do Not Sell signal. Counting the domains, as opposed to the individual requests sent, appears to make more sense as it is enough for a site to receive one request for Do Not Sell to be effective. The counter can be shown in the popup or on the settings page. @asalia-1 will be on the lead on this one, possibly, with some input from @kalicki1.

**Comment by asalia-1** [comment]
This issue can be closed since the counter has been implemented and pulled to master. Any adjustments to design will be discussed in issue #116
