### ISSUE TITLE
Add functionality to detect a site's .well-known.gpc.json response and add some visual

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#104]
As @dknopf mentioned in our discussion today, we may want to display a site's response to receiving a Do Not Sell signal as the site expresses it in its `.well-known.gpc.json` file. Essentially, this means to check for every site visit whether there is something available at www.example.com/.well-known.gpc.json. If so, retrieve that content and display it in OptMeowt. There are various points this functionality may touch upon, among others, OptMeowt's performance and where and how in OptMeowt this content should be displayed. For the time being this is not urgent and we can make this issue more concrete later on.

**Comment by SebastianZimmeck** [comment]
As @kalicki1 suggested, we may want to have the icon fully green for half a second or something like that. In addition, maybe some explanation or visual or UI design element in the popup to explain what the fully green icon means.

**Comment by kalicki1** [comment]
I implemented the .well-known green icon functionality in the last commit I pushed to this issue. Once we merge our open pull request regarding the Firefox fixes, we can merge this issue into the main branch as well.

**Comment by SebastianZimmeck** [comment]
Excellent!

**Comment by SebastianZimmeck** [comment]
Feel free to close, @kalicki1, if you feel this is done.
