### ISSUE TITLE
Use NPM to manage packaging (and possibly build process)

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#106]
Explore and implement how to package (and build) our extension. We also want to document in a section of the readme how to do it.

**Comment by asalia-1** [comment]
Integrated OptMeowt with npm to manage dependencies and grunt to automate the build process. Grunt is a task runner which is being used to carry out build operations. Currently, we are using grunt to compile relevant files needed from node_modules. The ground work has been laid to automate more parts of the build process using Grunt when the need arises. This task is done. I performed manual tests to make sure all functionality is forward compatible but I will have one last manual testing session with @kalicki1 to ensure that merging is safe. Afterwards, this issue will be closed. This is the pr associated with this issue: [issue-106](https://github.com/privacy-tech-lab/optmeowt-browser-extension/pull/108)

**Comment by asalia-1** [comment]
Next step is to have a testing party with @kalicki1 to ensure there are no loopholes or breakdown in functionality.

**Comment by SebastianZimmeck** [comment]
@kalicki1 will look at this and close if nothing remains to be done (maybe, there is something to do related to Firefox (issue #110).

**Comment by kalicki1** [comment]
@asalia-1 has been working on this issue and mostly finalized it. We implemented these changes into our Firefox release, which we should be ready to push to the Firefox add-ons store this week. However, I do think it is worthwhile to keep this issue open for another week or so so that we can fix one more library that was giving us some trouble.

**Comment by asalia-1** [comment]
There was one library (animate.css) preventing the closure of this issue. I have migrated this library and it is now being managed npm.
