### ISSUE TITLE
Distinguishing HTTP requests that should receive a Do-Not-Sell signal from those that do not

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#11]
As @davebaraka pointed out yesterday, many of the domains our HTTP browser extension communicates with should not necessarily receive a Do-Not-Sell signal. For example, if there is a simply an image being served, it may not be necessary to send a Do-Not-Sell signal to the respective domain.

@davebaraka suggested that there may be a way to distinguish based on the different categories shown in browser developer tools. Another (roundabout) way may be to filter out domains based on a list of content delivery networks (CDNs, e.g., Cloudflare). Though, it depends a bit on what they are actually serving.

At the moment, while nice to address, I do not see this issue as a big problem. In principle, it should not harm to send more Do-Not-Sell signals than actually needed. It is a bit similar to sending repeated signals while a user is already opted out (though, in that case, there may be actually a reason to do that, for example, if the opt out expires at some point).

Where I could see this issue coming up as well is in the [count of opted out services](https://github.com/privacy-tech-lab/privacy-rights-platform-browser-extension/issues/10). The count may be not accurate if pure administrative servers that just send content are included, for example.

(cc'ing @rgoldstein01)

**Comment by SebastianZimmeck** [comment]
As @kalicki1 observed during his IAB tests, sometimes OptMeowt places an extra opt out cookie for the `google` domain. In principle, this is not a problem (assuming that Google itself is not selling personal data, which seems to be the case according to its privacy policy). This is just another situation where an extra cookie will not have any effect (maybe, performance is an issue, though we would need to look into it).

@kalicki1 says:

> Right, my guess is this is the case when 3rd party cookies are not disabled on sites that use Google's ad network, but Google's cookie popping up on another site is the only case of this I've seen.

**Comment by SebastianZimmeck** [comment]
Bonus: @asalia-1, please finish this by our meeting next week.

**Comment by SebastianZimmeck** [comment]
Let's exclude image types and err on the side of rather sending one Do Not Sell signal too many as opposed to omitting one that should have been sent.

**Comment by asalia-1** [comment]
We are filtering image type HTTP requests and we are not attaching dns headers to them on interception
