### ISSUE TITLE
Fix Dependabot alerts

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#112]
@asalia-1, @kalicki1, and @dknopf, I changed your permissions such that you should now can view the Dependabot alert. It would be good if you could fix those, @asalia-1. They do not necessarily need to be all implemented (although, if there is no version conflict or other breakage, such implementation would be my preferred choice). However, take a look at each of those going forward and make a call whether or not to fix. If you have any doubt, please let me know.

**Comment by asalia-1** [comment]
Sure thing. And I will keep an eye out for future alerts

**Comment by asalia-1** [comment]
Looked into the security risks associated with the dependencies that were flagged and found the risk involved is tolerable for our use case thus we can safely ignore these alerts. I will keep an eye out for any of these alerts going forward and analyze them case by case to make sure they do not cause issues.
