### ISSUE TITLE
Kuba's laptop's issues with Firefox

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#115]

**Comment by SebastianZimmeck** [comment]
I installed OptMeowt on Firefox (version 83) on my computer (macOS Catalina version 10.15.7) and everything worked as expected. I checked on all sites:

https://globalprivacycontrol.org/
https://global-privacy-control.glitch.me/
https://www.privacytechlab.org/optmeowt/

When I turned the signal on, it was shown that I am sending it. When I turned it off, it was shown I am not sending it. Also, the DOM property was fine. Not sure what the issue could be ...

**Comment by kalicki1** [comment]
Okay, I just took some time to look at this issue and it turns out that since I don't regularly use Firefox at the moment, I forgot I had a few other GPC compatible extensions installed. I believe one of them must have had the DOM signal set to off by default, which gave us the `false` flag on the original demo server. Uninstalling all of them brought everything back to normal and it runs smooth. 

Given there doesn't seem to be an issue at the moment, we can close this, and I think we should be good to start the process of uploading to the Firefox add-ons store, @SebastianZimmeck.
