### ISSUE TITLE
Popup UI — counter & .well-known integration

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#116]
Let's use this issue to discuss and implement the redesign of the popup to integrate a .well-known information badge as well as a domain counter. (#102 references the domain counter, and #104 references the .well-known integration. Once that is complete we can work on that here.)

**Comment by kalicki1** [comment]
I just pushed a commit that includes a green badge within the popup when it is opened on a site that accepts the GPC signal. At the moment, the implementation currently checks to see if a `GPC.json` file exists, and then automatically sets the badge to inform the user that that particular domain will actively accept a GPC signal. Otherwise, the badge is not displayed to the user. 

Here is a screenshot of the current implementation: 

<img width="353" alt="Screen Shot 2020-12-07 at 4 56 43 AM" src="https://user-images.githubusercontent.com/60238705/101336548-9dbad500-3848-11eb-85d0-128c92a57338.png">

**Comment by SebastianZimmeck** [comment]
@kalicki1 finished the detection of the .well-known site. On the long run, we are also interested in surfacing its content (issue #125).
