### ISSUE TITLE
Google Sheets do not load at all

### ISSUE THREAD

**Issue by Samour50** [privacy-tech-lab/optmeowt-browser-extension#123]
Google Sheets do not load at all due to the browser extension.
Even when disabling do not sell on all google domains it still fails to load due to the site being unable to process the gpc flags. Google Docs and Drive load fine. Only option is to completely disable the extension.

This was working fine before as recently as yesterday so you may want to test and identify the root casue

**Comment by kalicki1** [comment]
Hey @Samour50! Thanks for the heads up!

I took a quick look at what the issue could be on my machine, though I wasn't able to replicate the issue. For my test I was using: 
- Chrome (87.0.4280.67 (Official Build) (x86_64))
- MacOS Big Sur (11.0.1)
- OptMeowt (v1.1.1, current Chrome Web Store version) 

Do you mind sharing a little more information about what web browser, it's version, and the OptMeowt version you're using? If you're using a specific Git commit, that would be helpful to know. If you feel comfortable, it would also help to know what other extensions you have installed in case there are any conflicts. Let me know, and we will look into the issue further!

**Comment by kalicki1** [comment]
Given that we have not been able to replicate this issue and that we have not heard back about further problems related to this issue, we will assume it has been resolved and close this discussion.

**Comment by kalicki1** [comment]
@Samour50, if you find this problem recurring, feel free to open this issue back up.
