### ISSUE TITLE
404 Error When .Well Know Not Found

### ISSUE THREAD

**Issue by dknopf** [privacy-tech-lab/optmeowt-browser-extension#138]
I'm not sure if this is intended or not, but on any site that doesn't have a .well-known/gpc.json file there is a 404 error. This happens even when the extension is disabled via the popup disable button.

![image](https://user-images.githubusercontent.com/7244624/107410712-a8f5df80-6adb-11eb-83ba-5077450f3c71.png)

**Comment by SebastianZimmeck** [comment]
Good point, @dknopf. I believe I mentioned that a while back to @kalicki1 and we settled on being OK with those 404s. (There is essentially no way around those, as I see it.)

**Comment by dknopf** [comment]
Yeah I figured you guys had seen it, I was just wondering if there was some way of suppressing the error and instead printing out a message or something, just so that other developers don't think there's a problem in our code.

**Comment by kalicki1** [comment]
So I just took a look at the error, and yes I agree with @SebastianZimmeck that the 404s are probably alright. I would hope developers would be able to see the 404 is on the 1st party's hands for missing a `.well-known`, not ours. I think the more concerning thing was that the extension would continue to send content scripts regardless of whether OptMeowt was enabled or not. I'm pushing a change that will turn off `contentScript.js` when the extension is disabled, which shuts off all action on a page for good.

**Comment by SebastianZimmeck** [comment]
Maybe, add a sentence to the readme that not finding a `.well-known` will cause a `404` error.
