### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#141]
I think we should also create a new release. Especially, the Chrome and Firefox version are currently not the same.

**Comment by kalicki1** [comment]
I created a new tag and published a new release @SebastianZimmeck. I have also pushed our new version to the Firefox AMO store and just received email confirmation that everything is all set. I think you should be all set to update the Chrome Web Store version the same way when you have the chance!

**Comment by SebastianZimmeck** [comment]
Great! Thank you, @kalicki1. I just submitted v1.1.4 on the Chrome Web Store as well. I will close this issue once it passes review there.

**Comment by SebastianZimmeck** [comment]
OK, we have v1.1.4 on Chrome Web Store and the AOM store.
