### ISSUE TITLE
Devise approach on identifying Do Not Sell links 

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#149]
Per @stanleymarkman's findings, sites subject to the CCPA sometimes use language in their opt out links different from what the CCPA requires. Thus, we want to come up with an approach to match the diverging links. This approach can be as simple as providing a set of all the links that we encountered so far. Regular expressions or [string distance metrics](https://en.wikipedia.org/wiki/String_metric) are other options (which, however, we only should approach if creating a set of strings does not work sufficiently well).

**Comment by kbeliauski** [comment]
I am going to add a list of all the different links we have seen so far. We can see with time if we have to go with a different solution. I am thinking to connect the functionality to a button in a popup of the extension, so that when a user presses it, we can check if the website has the link or not. another idea that just came to mind is that we can have a text field that will show the results of the search for the link that would happen automatically for every website.

**Comment by kbeliauski** [comment]
it doesn't really matter what we go with, because it will barely affect my code that I am writing right now.

**Comment by SebastianZimmeck** [comment]
> a button in a popup of the extension, so that when a user presses it, we can check if the website has the link or not.

I would say what we definitely should have is a functionality that automatically checks whether a Do Not Sell link is available as soon as the user navigates to a new site. The more we can do automatically, the better.

There may be also the problem that a site only has a link on its homepage but not on other pages. I have not looked too much into this. So, this is a bit of a question how it is done in practice and requires to look at a some sites. If there is a substantial amount of sites with links only on homepages, we should think whether there is a way to get the link from the homepage if the user is on some non-homepage site (I would guess not, but that is something to find out first).

**Comment by kbeliauski** [comment]
I am closing this issue for now after looking for the best way to find the links on the pages of the website that are not the home page. The only good way to do it now is to use the site crawlers that are written in python as javascript doesn't have this kind of functionality. In addition, after we refactor the UI, I can either reopen this issue or open a new one where I will focus on identifying the links that named in a different way in comparison to the standard way the CCPA requires.
