### ISSUE TITLE
Feature Request: Add option to disable extension console logs

### ISSUE THREAD

**Issue by dziku86** [privacy-tech-lab/optmeowt-browser-extension#150]
As in the title. Add option to disable optmeowt extension console logs.

**Comment by SebastianZimmeck** [comment]
We will look in that ...

**Comment by kbeliauski** [comment]
I am working on it right now. I will add the function when depending on the status of the switch, we will be able to remove or leave the console logs. In addition, I think it will be a good idea to make this a button in the interface of the extension, so that any user can just choose to remove them.

**Comment by kalicki1** [comment]
For the time being, I pushed a small change that comments out the console.log's we are currently using.

**Comment by SebastianZimmeck** [comment]
@kbeliauski, please create a PR and add @stanleymarkman and @kalicki1 as a reviewer.

**Comment by kbeliauski** [comment]
currently waiting for @stanleymarkman to merge his changes, so that I can make a PR. Currently, the feature is partially working, so I would like to get some feedback from @stanleymarkman or @kalicki1 about how to improve it.

**Comment by kbeliauski** [comment]
The solution I have been thinking about is making the function, that allows to turn off the logs, an export function, and then import it to every file that has console logs calls in it.

**Comment by SebastianZimmeck** [comment]
> currently waiting for @stanleymarkman to merge his changes ... so I would like to get some feedback from @stanleymarkman or @kalicki1 about how to improve it

Yes, the issue I see at the moment is that we need to fundamentally restructure our architecture before we can get to these more detailed issues. For the time being, in situations like these we can push to feature branches. Concretely, @kbeliauski, feel free to open an `issue-`150` branch and push it to the remote repo. That way the change is at online, possibly for @stanleymarkman or @kalicki1 to take a peek, and we can merge it later into the main branch.

**Comment by kbeliauski** [comment]
pushed a branch `issue-150`. Will be updating after the feedback.

**Comment by kbeliauski** [comment]
After @kalicki1 looked at the code, we decided that I will create an export function for the console log switch function that currently only works for the popup window and will import it to every file that has logs.

**Comment by SebastianZimmeck** [comment]
@kbeliauski, you will finish this in the next days, right? (I believe that is what we discussed.)

**Comment by kbeliauski** [comment]
Yes @SebastianZimmeck, I am finishing it this weekend in addition to working on other more urgent issues.

**Comment by kbeliauski** [comment]
Right now we are refactoring the whole codebase, so I will close the issue for now since I don't see a point to implement this change right now and then redo it with the new code. Will work on this once everything is set.
