### ISSUE TITLE
Use built in classification flags to find tracking requests

### ISSUE THREAD

**Issue by stanleymarkman** [privacy-tech-lab/optmeowt-browser-extension#162]
Wow! wish I'd found this earlier- looks like the API (at least for firefox) has some kind of way to filter for tracking, ads, and analytic flags. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onSendHeaders
(look under 'The classification flags include')
Definitely will be good to research and implement this.
(part of https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop)

**Comment by SebastianZimmeck** [comment]
@stanleymarkman, it would be good if you can explain a bit more at our meeting later today.

**Comment by SebastianZimmeck** [comment]
As we will be concentrating on the privacy flags after our 2.0.0 release, I am closing this. Nice find, @stanleymarkman!
