### ISSUE TITLE
Merge privacy compliance functionality into main branch

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#163]
As discussed today, it may be worthwhile for @stanleymarkman to bring in his changes for the privacy compliance functionality --- checking whether a privacy flag was changed to restricted data processing mode after an opt out --- fairly soon. The reason is that the longer we wait with the merge, the more difficult it may get. As far as I am concerned, it is OK if the main branch breaks. We can figure that out ...

This also affects @kbeliauski's work. Especially, it may make sense to wait until the merge is completed before @kbeliauski merges issue #150.

**Comment by SebastianZimmeck** [comment]
I think before we do this merge, we have to figure out the HTTPS situation (issue #161, which is currently the most important issue if I see that correctly). Essentially, if we are not able to decrypt HTTPS traffic for Google Chrome (which seems the most likely outcome at this point), we may have to create two separate OptMeowt versions --- one for Firefox with the privacy flag compliance functionality and one for Chrome without. In that case we will need to rethink a bit the structure of the code and how we organize the repo.

**Comment by kalicki1** [comment]
If we want to restructure the code, one of the ideas I had that would be most valuable to us is to restructure the code to work in a fashion similar to how the [DDG Privacy Extension](https://github.com/duckduckgo/duckduckgo-privacy-extension) code base is structured. I haven't looked at it in a while, so I don't remember the details of how it works, but some of the main things I would like are possibly using [Browserify](https://github.com/browserify/browserify) to package our extension. This would then allow us the flexibility to use more Node.js style structuring, which I think could simplify things for us. This could also allow us to manage a Firefox and Chrome code base with as many shared files as possible (see the `shared` folder in the DDG GitHub).

They break up the code and pass modules and information around in a much more clever way than we do at the moment, I think this is worth looking into. This could be its own branch, however (possibly multiple). 

Without looking at the details of @stanleymarkman's code, it might be worth it to merge your stuff in first, fix whatever breaks, and then refactor per what I mentioned. This is especially if you will keep adding stuff you will be using for the time being.

**Comment by SebastianZimmeck** [comment]
This issue is essentially subsumed by #165. 

(@stanleymarkman and everyone actually, please close issues if they are done.)
