### ISSUE TITLE
[Frontend] Rewriting current frontend with React

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#168]
Let's use this issue to discuss / work on rewriting our frontend (the options page and popup) with React. @stanleymarkman @kbeliauski, you both mentioned you have experience working in React so this might be something easier for either of you to take a look at when you have time. We can also brainstorm ideas for how to implement a streamlined frontend codebase here as well. Linking issue #165 as well.

**Comment by stanleymarkman** [comment]
I'll get started on the React rewrite- the next step in the analysis functionality requires some fairly substantial UI additions, so I'll start out by writing the analysis frontend first. By the time I'm done with that I should understand how the frontend should be structured and I'll go back and start putting back the features from the current Optmeowt UI. Let me know if any UI features should take priority- wanted to get started on this so the more crucial analysis features can go ahead.

**Comment by stanleymarkman** [comment]
@kbeliauski the database system will need to be linked in with the new UI eventually- I'll make sure to document the UI hooks well to make it easier when we need to link them.

**Comment by SebastianZimmeck** [comment]
We close this issue until we have more concrete UI elements to implement, at which point we will open new issue(s). @stanleymarkman will be taking care of this.
