### ISSUE TITLE
[Frontend] Designing Chrome vs. Firefox UI

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#169]
Let's use this issue to discuss how we will implement a Firefox UI with our privacy analysis functionality and/or if we need to make changes to how the Chrome UI will look as a result. It might be the case there is not much to decide, in which case we can close this issue early. @stanleymarkman started off with some good ideas on what we could do with our badge icon on different ad calls, etc. We can write those up here and discuss. 

Also as a side note, instead of fully rewriting the frontend with React and porting exactly as the frontend is now (issue #168), we can also do a redesign and implement that if we feel that's what needs to be done instead.

Mentioning issue #165.

**Comment by SebastianZimmeck** [comment]
As I see it at the moment, much of the compliance analysis UI could be relegated to a Compliance Analysis Settings page (or something similar) in addition to About, Domain List, and About. The current Compliance Analysis popup button, per below, is for starting the analysis functionality, and all other details are displayed in the settings page:

<img width="310" alt="Screen Shot 2021-06-04 at 10 05 47 PM" src="https://user-images.githubusercontent.com/11034003/120876848-32488a80-c581-11eb-99a6-1216a216e346.png">

Just a thought. Not necessarily totally fleshed out.

On a side note (and maybe for a separate issue), I feel that Dark Mode and Compliance Analysis should be changed in order and Compliance Analysis should be more prominent as it is really core functionality. Dark Mode is just a setting.

**Comment by SebastianZimmeck** [comment]
I am closing this for now as the questions for me is going beyond the UI and is an architectural one (one extension or two? how to structure the code? ... ). Once we have resolved this fundamental question, we can tackle the UI again.
