### ISSUE TITLE
New dev environment using Webpack to build Firefox & Chrome versions

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#179]
This is the last big sensitive refactoring issue. Ideally, we will have one repo for both the Chrome and Firefox versions we will be developing. However, since the Firefox version will be diverging from Chrome in the near future, as well as for the sake of codebase simplicity, we need to find a way to abstract away the browser specifics from the code base and use some sort of javascript compiler and task runner to build the version of the extension we want during development. 

One way to implement this is to have two separate `events.js` and `background.js` files, i.e., `firefox-events.js` / `chrome-events.js`, etc., and then have a task runner chose which files to build when we test/distribute. The other way I am thinking is to have a more "combined" repository, and use a task runner to fill in the browser we choose, i.e., have all the functions necessary for each browser together and then use $BROWSER or some other keyword in place of the browser name which the task runner will fill in. I'm leaning towards the first option, though we will still need to make sure we update both Chrome and Firefox versions for new functionality that should be included in both. 

I will take a look at this once issue #178 is all set since we could use this implementation, ideally with a task runner and Babel/Webpack, in order to use better node libraries in place of what we use, as well as simplify our code base.

**Comment by kalicki1** [comment]
@stanleymarkman @kbeliauski, if you have any experience with this, please feel free to pitch in!

**Comment by SebastianZimmeck** [comment]
> since the Firefox version will be diverging from Chrome in the near future

I am thinking ideally there would be one common codebase that works for both Chrome and Firefox and then a module (with the Cal AG compliance functionality) only for Firefox.

**Comment by kalicki1** [comment]
@SebastianZimmeck, yes that is what I have in mind as well! I guess this issue is for handling the differences between the few listeners in `background.js` that take different parameters in Firefox vs. Chrome, since we still have separate functions per browser. I think having our extra `if` statement works, but just doesn't feel as elegant as it could be 😅

If we want to, I guess we could simply just have a check in the code itself along the lines of `if (browser == firefox) then run_firefox_module` rather than having a task runner/compile add it to the code. Either way, I think implementing a task runner and a compiler will be useful.

**Comment by SebastianZimmeck** [comment]
> code itself along the lines of if (browser == firefox)

Yes, is there possibly some standard way of doing this or even APIs? I imagine there are other people developing one codebase for different browsers. For example, in React Native there is a standard way of specifying which code should be run for iOS and Android.

@kbeliauski, once you have time, can you find out more ... ?

**Comment by kbeliauski** [comment]
Yes, I can look for how to maintain the same codebase easily. I will write what I find here!

**Comment by SebastianZimmeck** [comment]
> I will write what I find here!

And implement it.

**Comment by kalicki1** [comment]
I just pushed some changes in issue #166 that begin to address this with simple Webpack functionality.

**Comment by kalicki1** [comment]
This is related to issue #176 because it involves using the frontend with Webpack, as well as #166 broadly. 

I just pushed a commit in branch issue-166 (omnibus refactoring branch) that connected Webpack to the popup using html and css loaders (see the `webpack.config.js` for specific names of loaders). Though this would better be discussed more in depth in another issue, I am just making a note since I am implementing Webpack and discussing it here.

**Comment by kalicki1** [comment]
Something that might be useful down the line is Mozilla's [Webextension `browser` API polyfill](https://github.com/mozilla/webextension-polyfill). As mentioned at the top of the repo: 

> This library allows extensions that use the Promise-based WebExtension/BrowserExt API being standardized by the W3 Browser Extensions group to run on Google Chrome with minimal or no changes.

I.e., APIs that run in the promise based `browser` namespace can be used in browsers that don't support it, e.g., Chrome.

**Comment by SebastianZimmeck** [comment]
Good find, @kalicki1! Just to clarify this would not mean that the [HTTP analysis functionality](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/filterResponseData) on which we rely would become available for Chrome, right? It is just that whatever Firefox API is also available on Chrome would be translated over from Firefox.

**Comment by kalicki1** [comment]
That is my impression of the polyfill, @SebastianZimmeck. As far as I can find, it should only translate the APIs available to both Chrome and Firefox, though this is something I can test with a sample project.

**Comment by SebastianZimmeck** [comment]
It seems many people are wondering that. :) So, they included the following in their [readme](https://github.com/mozilla/webextension-polyfill) (confirming our understanding):

> This library doesn't (and it is not going to) polyfill API methods or options that are missing on Chrome but natively provided on Firefox, and so the extension has to do its own "runtime feature detection" in those cases (and then eventually polyfill the missing feature on its own or enable/disable some of the features accordingly).

**Comment by kalicki1** [comment]
Just pushed a commit referenced in issue #166 regarding the first major development environment regarding building for Firefox and Chrome.

The new commit in branch issue-166 adds two new files, `listeners-firefox.js` and `listeners-chrome.js`, which are called implicitly from the now even more streamline `background.js` via `import . . . "listeners-$BROWSER.js"`. I added the `string-replace-loader` node module as a loader in Webpack which searches for `$BROWSER` via regex and replaces it with the chosen browser (`firefox` or `chrome`, all in `webpack.config.js`). 

The new main functionality hierarchy is as follows: 
`HIERARCHY:   manifest.json --> background.js --> listeners-$BROWSER.js --> events.js`.

This way, if we ever need to do browser specific work, i.e. in the frontend, we can simply import according to `$BROWSER`. 

This is my solution to this problem for the time being. I will also make mention we looked at the following but decided it wasn't right for this particular job: 
- [browserlist](https://github.com/browserslist/browserslist) 
- Forcing different entry points via Webpack without substitution
- Webpack targets? (was suggested, didn't look too far into it)

Hopefully this will work as a long term solution!

**Comment by kalicki1** [comment]
As I have implemented this functionality at the most basic level, I will go ahead and close this issue. 

If we find bugs related to the developer setup and how we compile for Firefox and Chrome, we can open this back up at another time in the future.
