### ISSUE TITLE
Headless Mode & Automation

### ISSUE THREAD

**Issue by stanleymarkman** [privacy-tech-lab/optmeowt-browser-extension#180]
I looked into our idea about pivoting the current extension to do automated analysis and data collection on a set of websites.
The main difficulty with this is the sandboxing around Mozilla/Chrome extensions. Large-scale data collection would involve simulating requests to a bunch of websites in the background, hidden from the user. As far as I can tell, this isn't possible to do fully via an extension. Instead, we'd need to use some sort of automated webcrawler. 

Selenium could work well with Firefox's webdriver api- the problem is, a headless instance of firefox can't 'legally' be launched from within an extension. To automate data collection with our current setup, we'd need to spin off the headless functionality into a binary, downloaded separately from the rest of the extension files. This does overcomplicate things especially with downloading foreign software to the AG's computers.

It might be best to put the automated/headless idea on the backburner for now, and eventually continue to explore automated data collection via the extension.

**Comment by SebastianZimmeck** [comment]
I agree with you, @stanleymarkman. As I see it, the actual analysis capabilities of our extension are much more important than automating it or applying it at scale. I think it may work best if the user just visits a site they want to analyze and then the analysis is performed for that site.

**Comment by SebastianZimmeck** [comment]
As we decided for the time being to not do any automation or use tools beyond the extension, e.g., Selenium, I am closing this issue.
