### ISSUE TITLE
Migrating libraries to Node packages

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#182]
As @stanleymarkman mentioned, we'll just go ahead and delete all of our libraries and add them back in with Node package substitutes when we find something breaks.

**Comment by stanleymarkman** [comment]
Idea on how we can do this- disable/delete the entire library folder, install node modules one-by-one as we get reference errors

**Comment by stanleymarkman** [comment]
From now on, due to the webpack setup all dependencies can be added at build time instead of stored in libs/

**Comment by kalicki1** [comment]
I just pushed a commit that removed all of our libraries from the extension. 

I managed to fix most of the popup, at least with respect to looks without fixing any functionality. The dark mode lib will take a little bit more work to make functional again as well.

**Comment by SebastianZimmeck** [comment]
Great! Yes, the dark mode is not horribly important.

**Comment by kalicki1** [comment]
As @stanleymarkman has mentioned he managed to get the options page working to some extent, I will leave alone re-implementing all of the frontend libraries via node modules instead of our old method of using the local `src/libs` folder. 

Since this is the case, I will go ahead and close this issue and open a small one regarding dark-mode so we do not forget.
