### ISSUE TITLE
For new release switch to minified js dependencies

### ISSUE THREAD

**Issue by stanleymarkman** [privacy-tech-lab/optmeowt-browser-extension#185]
When I added back the dependencies into the webpacked refactoring of the extension, for debugging purposes I used the unminified version wherever possible. This causes webpack to throw warnings, though, since the popup/options entrypoints are now pretty big (>3mb each). I don't think this is that big of a deal, especially for an extension rather than a webapp, but before release we should switch all dependencies in options.js and popup.js to minified.

**Comment by SebastianZimmeck** [comment]
I am closing this issue as @kalicki1 mentioned that the Firefox extension review requires unminified libraries. Given that webpack still works, just with warnings, I think it is OK. Feel free to reopen if you prefer @stanleymarkman.
