### ISSUE TITLE
Fixing popup

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#187]
This is related to refactoring OptMeowt issue #166. 

I am close to finishing reconnecting the popup OptMeowt, over the next couple of days I will push the related changes.

**Comment by kbeliauski** [comment]
I am going to continue working on this issue while @kalicki1 works on adding the cookies functionality back. 

Things we have to do to fix the popup:

- [] fixing the storage method 
- [] making sure that everything in the DOMContentLoader [here](https://github.com/privacy-tech-lab/optmeowt-browser-extension/blob/c34a2457464c4768aff4247d0ceea74793d99772/src/popup/popup.js#L58)
- [] fixing the 3rd party domains logic
- [] fixing the website response part
- [] test everything works

**Comment by kalicki1** [comment]
I managed to finish off the rest of the work related to this issue. Since the bulk of the work here is done, I will go ahead and close this issue. Thanks @kbeliauski for your work on this!
