### ISSUE TITLE
Fix domainlist not generated in options page

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#190]
One of the outstanding broken features of our codebase is that the domainlist page on our options page doesn't populate with the user's domainlist. Let's use this issue to track those fixes.

**Comment by kalicki1** [comment]
I'm not sure if these changes exist yet and just need to be pushed or if this is something we need to work on. @stanleymarkman, I think you may have been looking at this, do you have any updates on it or should we both take a look?

**Comment by SebastianZimmeck** [comment]
Closing as it is already fixed.
