### ISSUE TITLE
3rd Party Domains don't reset between page loads on Popup

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#192]
This may be related to how the requested domains are cached in `events.js`. We will need to add a reset that clears this between page loads.

**Comment by kalicki1** [comment]
It looks like this may actually be a bug from our old code.

 I think it is an edge case bug that was never found out because it only shows itself when you keep reloading new sites without switching tabs. Only then do all the old requests continue to show without clearning themselves, i.e., you visit `google.com` and the third party domains are 

1) `google.com`
2) `gstatic.com`
3) `doubleclick.net`

then navigating to `duckduckgo.com` without switching tabs and reopening the popup shows 
 
1) `google.com`
2) `gstatic.com`
3) `doubleclick.net`
4) `duckduckgo.com`

Switching tabs appears to force a reload and wipe the cached requests. I will go ahead and play with which web blocking APIs will allow us to clear this cache properly without losing data related to the new request.

**Comment by kalicki1** [comment]
I wrote up my notes here so I don't forget, apologies for the long comment. Feel free to skim or even to read just read the summary. 

## My tests

So I ran a few tests with the tools we already use (namely the `webRequest` & `webNavigation` APIs) and here is what I found. Just so its documented, the line of code I want to run to clear our per tab requests cache is 
`tabs[activeTabID].REQUEST_DOMAINS = {};` based on the structure of our current 

1) `webRequest`

I ran this line of code with a few console.logs in `webRequest` APIs, but the problem is that they are triggered on every single small page element. This is not good, bc then the cache is cleared almost fully by the time the page is done loading. We don't want this. 

2) `webNavigation`

This is our next best bet, but Google writes that this is approximately based on what a user sees, not necessarily per each request on a page. The two calls I wanted to test were `webNavigation.onBeforeNavigate` and `webNavigation.onCommitted`. [See the order they're called in the docs here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation). 

I first tested how many domains persist across a page change with `webNavigation.onBeforeNavigate`. 

First I visited Yahoo, recorded the 3rd party domains, then visited DDG and saw maybe two holdovers from the previous call. 

<img width="600" alt="yahoo to duck - onBeforeNavigate" src="https://user-images.githubusercontent.com/60238705/126584649-45bc97ae-2ffe-474b-952d-2ecb1441efdf.png">

This isn't so bad, aside from the fact we may lead users to think DDG is loading Yahoo and Google sources. 

My next test was with `webNavigation.onCommitted`. I found there was no holdover from Yahoo to DDG in the first test, but for some reason `duck.com` was actually dropped. This leads me to think this API might drop 3rd party domains from the currently visited site, which is not great. 

<img width="600" alt="onComitted - yahoo to ddg" src="https://user-images.githubusercontent.com/60238705/126584727-7600f355-ca74-4c0c-a2c3-7dbd7580d6a6.png">

I think this may be the case because navigating to Yahoo, and refreshing just to make sure most the domains are showing, still yields the following requests to many fewer domains than in the first screenshot in the `onBeforeNavigate` test.

<img width="600" alt="onComitted 2 - yahoo to yahoo" src="https://user-images.githubusercontent.com/60238705/126584778-c649327e-8027-4b14-8852-7ab9326e7c4e.png">

I'm not a huge fan of this, as a user I'd like to see all the info that there should be if I'm asking for it. 


## The big problem

Overall it just seems that `webNavigation` does not allow us to grab the moment when a page is refreshed/called/navigated to exactly when it happens. As the documentation says, it's all relative to how the UI loads. This is a problem if we want the requests precisely associated with this user request. 

## What to do

1) We could create an apparatus in the code using both APIs and boolean flags, and potentially predictive power (e.g., what HTTP requests were made in the vicinity of the user page request), though this will take time and trial and error. It will also be a best guess in the end. 

2) I think it might be possible that the `cache` API would allow us to save which requests correspond precisely with the start of a user page request, though I'm not sure. This would also take some time to research. 

3) Just pick one of the `webNavigation` APIs to approximate what we want. 

## My suggestion

The simplest solution is to just use `webNavigation.onBeforeNavigate`, since that is the first of the `webNavigation` APIs to be triggered, even if we do end up retaining, for some reason I could not find out, some requests from the previous page. 

This may be confusing, such as when `google.com` shows up as a 3rd party domain on `duckduckgo.com`, but this may be better than having all past 3rd party domains persist. We can potentially use this method but show a disclaimer that the 3rd parties list is imprecise if you do not refresh after navigating somewhere (no one will do this in practice, and even then it's not 100% certain everything will be there based on what I could tell).

**Comment by kalicki1** [comment]
This could also take research into what constitutes a navigation event and what info we can get alongside one.

**Comment by SebastianZimmeck** [comment]
Thanks for writing this up, @kalicki1! Let's discuss this tomorrow, so that I fully understand how much of an issue this is.

**Comment by kalicki1** [comment]
We discussed this a little bit today and have decided to keep this issue open for the time being, with the implication that my temporary patch utilizing a cache clear function on `webNavigation.onBeforeNavigate` will do fine. The tests mentioned below don't really provide an advantage over the `onBeforeNavigate` API, but it's good to note what was discussed.

**Comment by kalicki1** [comment]
@stanleymarkman suggested a few good points to note. He pointed out it may be the case it is not necessarily our fault the API is a little imperfect. He suggested 

> What if webNavigation is giving us the exact moment of page-switch, but the following happens:

> 1. user navigates to site A, which initiates a third-party request 2. before third party request completes, user navigates away from site and domainlist is cleared 3. third-party request is completed and logged for a website no longer opened by user

He also suggested that if this is the case, we could look into what events occur on a javascript `onUnload` call, since it may also be the case that 

> our code is detecting last-minute requests sites make when the user navigates away- for example, if you close a Yahoo tab they might initiate a last-second message to ad providers telling them how long a user spent on their site.

The last thing @stanleymarkman mentioned was checking whether certain firefox config settings could show us this is the case or if they could be a solution, such as disabling `beacon.enabled`, `dom.disable_beforeunload`, or playing with `dom.beforeunload_timeout_ms`.  I tested out the first two of these and unfortunately, I did not see a change in behavior. 

@ekuller also mentioned briefly in lab that I could also run a test by clearing my cache on receipt of a content script message that is initialized on `document_start`.  I ran a quick, limited test on this and didn't find much of a difference between the old approach and the content script approach.

**Comment by SebastianZimmeck** [comment]
As @kalicki1 [said](https://github.com/privacy-tech-lab/optmeowt-browser-extension/issues/192#issuecomment-885305760). We keep this issue open in case we find a better solution over the next few weeks. If there is none, the current solutions is just fine and we close this issue.

(Note to self: in a nutshell this issue concerns that if you visit google, then ddg, then yahoo, etc., there may be some residual 3rd party domains still show in the popup without clearing; at the moment, these are only individual instances, and we can live with it.)

**Comment by stanleymarkman** [comment]
I also played around with the config settings I suggested- didn't seem to make a difference, sadly. One possible solution I can think of is using `webRequest.onCompleted.timeStamp`- grabbing the exact time in milliseconds the third-party request actually fired, and using that to determine which page the request should be attributed to. This might not fix the issue, but at least might tell us exactly where (or rather, when) these extra requests are coming from.

**Comment by kalicki1** [comment]
That's a good idea @stanleymarkman, that's something we can look into when we have some downtime. Since I think we are generally OK with the solution we have at the moment, I am thinking that we can close this issue while we prep for release. I am thinking we can make a note of this issue on the Wiki (maybe on a dev specific page?) just to have noted the way we solve this issue at this point in time.

**Comment by SebastianZimmeck** [comment]
> I am thinking that we can close this issue while we prep for release. I am thinking we can make a note of this issue on the Wiki (maybe on a dev specific page?) just to have noted the way we solve this issue at this point in time.

Agreed with both of you, @stanleymarkman and @kalicki1.
