### ISSUE TITLE
Fix export/import settings functionality from options page

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#193]

**Comment by stanleymarkman** [comment]
i/o functionality exists in previous commits- should only need to implement it directly into settings page, since this stuff isn't needed anywhere else.

**Comment by stanleymarkman** [comment]
Export functionality is now working, although I'm not sure if it's backwards compatable. @kalicki1 , any chance if you know if there's a saved domainlist from an old version, so I can test import functionality?

**Comment by kalicki1** [comment]
I don't believe I have any saved versions, but you can generate one from the old code. If you run a version of the extension prior to our refactor, visit a few sites, and export that, that should work!

**Comment by SebastianZimmeck** [comment]
If you feel it is necessary, @stanleymarkman (OK with me if not).

**Comment by stanleymarkman** [comment]
Import and exporting now works again. Warning: it's not possible to import a domainlist from any previous version of Optmeowt. If anyone really needs to in the future, they could just copy/paste the list of domains into a text file formatted like this:

`["domain1.com", "domain2.net", ...] , [true,false,...]`
