### ISSUE TITLE
Regression: DOM signal injector does not follow spec

### ISSUE THREAD

**Issue by eligrey** [privacy-tech-lab/optmeowt-browser-extension#195]
[Your DOM signal injector](https://github.com/eligrey/optmeowt-browser-extension/blob/main/src/dom.js) is still using the old implementation that I fixed in #142.

Consent managers may expect [a correct implementation](https://github.com/eligrey/optmeowt-browser-extension/blob/9be43907440708b742fb4b55b74ac94fb22fcf54/src/dom.js) to properly heed the GPC signal.

**Comment by SebastianZimmeck** [comment]
Thanks, @eligrey! We are currently doing a major refactoring, and I could imagine that change fell through the cracks. We will look into it ...

**Comment by kalicki1** [comment]
Thanks for the heads up, @eligrey! You're right, our last release, [v1.1.4](https://github.com/privacy-tech-lab/optmeowt-browser-extension/releases/tag/v1.1.4), does have [the bad DOM signal injector](https://github.com/privacy-tech-lab/optmeowt-browser-extension/blob/v1.1.4/src/dom.js). I'm not sure how this slipped through, but we do have the correct [injector implementation](https://github.com/privacy-tech-lab/optmeowt-browser-extension/blob/939b93c0e8d5c9a53a127e9b02ee73c64702eb52/src/background/dom.js) on our latest commit. 

As @SebastianZimmeck mentioned, we are refactoring our code and are actually planning on releasing this new version later this week, this should resolve the issue you mentioned!

**Comment by eligrey** [comment]
Thanks, glad to hear that this isn't slipping through the cracks

**Comment by SebastianZimmeck** [comment]
Closing this issue as the change is in the main branch and the release will come later this week.
