### ISSUE TITLE
Fix domain deletion and re-adding bug

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#202]
It seems that when I delete an individual domain from the domain list and later visit the deleted site again, it is not re-added to the domain list. I tested this for amazon.com and citi.com on the current Chrome version with the domain list setting enabled. It does not seem to make a difference whether I simply refresh amazon.com, open a new tab and navigate to amazon.com, or whether or not I have enabled the domain list setting. I have not tested this for Firefox. So, not sure whether this is a browser-specific issue.

**Comment by kalicki1** [comment]
Good catch @SebastianZimmeck. This was related to how we handle synchronizing the local domainlist cache and the domainlist in indexedDB. I pushed a patch that makes sure the two are in sync. We should be all set to close this, I tested it on Chrome on google.com and citi.com and the domains were added back in after being removed.

**Comment by SebastianZimmeck** [comment]
OK, great, @kalicki1! I tested it for both Chrome and Firefox, and it works now.
