### ISSUE TITLE
Remove `Undefined` from DOMAINS whitelist?

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#27]
@SebastianZimmeck and I noticed that when the DOMAINS whitelist is reset and first begins to repopulate itself, an `Undefined` entry always pops up. We are not sure why this is, but it is the only abnormal behavior we see at the moment. We can address this when we have time, since it doesn't seem to be causing any major issues at the moment.

**Comment by SebastianZimmeck** [comment]
@kalicki1 observed that this does not seem to occur any longer. @kalicki1, if you could confirm this and close the issue accordingly.

**Comment by kalicki1** [comment]
@SebastianZimmeck, yes I have been checking back on this issue every so often to see if it still comes up, but it does look like it somehow resolved itself/may have been a development issue. I agree, we should be able to close the issue now!
