### ISSUE TITLE
Clarify how extension works with notifications upon first install

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#32]
One way to clarify for the users how the extension works is to show notifications after installation.

For example, there was a new feature today in MS Teams, and it showed me the following notification. If possible, that is something we should also consider. I probably would not overdo it to avoid annoying users, but for one or two essential places this may be an option.

<img width="354" alt="Screen Shot 2020-06-12 at 9 32 06 AM" src="https://user-images.githubusercontent.com/11034003/84515517-91d7c700-ac9a-11ea-88f0-cb889ddf27c9.png">

1. Especially, at the moment the user has to turn on the extension to start sending Do Not Sell signals, which is good because the law requires an active decision. However, there could be a usability issue because normally users would probably expect that the extension works right after installing it. (On a side note, let's make the play button green or otherwise more obvious.)

2. Also, we have this little counter in the extension icon counting the Do Not Sell items. It is probably not totally clear what the number means.

To clarify these two points notifications may help (maybe just one covering both of these issues pointing at the icon right upon installation).

(cc'ing @davebaraka and @rgoldstein01)

**Comment by kalicki1** [comment]
Last week, @SebastianZimmeck, @davebaraka and I discussed how we can implement this issue as it pertains to issue #42. Our idea was that we should explain the DAA CCPA Opt Out protocol to users somehow, since it is a protocol that would ideally run one time and will be potentially intrusive to the user experience while it executes. 

@davebaraka suggested that I look into a form of an 'on install' api that we can use to walk users through the extension setup process as well as explain how issue #42 works before we run that functionality. 

Since issue #42 seems to have worked out well for now, I will leave this as a lower priority issue for when our core opt-out features are more solidified. This way I don't have to come back here to redo this extension 'tutorial' if major changes happen between now and when the extension is finalized.

**Comment by SebastianZimmeck** [comment]
@asalia-1, please finish this by our meeting next week.

**Comment by SebastianZimmeck** [comment]
@asalia-1, will change the color of the popup (uniform with other OptMeowt colors). Also, the overlay darker while popup is being shown.

**Comment by SebastianZimmeck** [comment]
Also, reduce to maybe three in the settings and one in the popup.

**Comment by asalia-1** [comment]
![popup2](https://user-images.githubusercontent.com/44120238/94447216-8dff8000-0177-11eb-8b1a-58e03cd17368.png)

There are 3 popups of such nature with overlay effect upon install to show user important sections on the options page.

![popup1](https://user-images.githubusercontent.com/44120238/94447299-9bb50580-0177-11eb-95e2-2c7113ca624e.png)

This shows up in the popup on after the very first install to give some info about the UI to the user

**Comment by SebastianZimmeck** [comment]
OK, what is the text for the remaining two notifications?

Could you change the following?
"Set your domain list preferences here" to "Set which sites should receive a Do Not Sell signal."
"Toggle this to enable/disable OptMeowt for this site" to "Toggle this switch to enable or disable sending Do Not Sell signals."

Also, they should only show up once after installing OptMeowt. Is that the case?

**Comment by SebastianZimmeck** [comment]
@asalia-1, please push to an issue-32 branch what you have so far.

**Comment by asalia-1** [comment]
![popup3](https://user-images.githubusercontent.com/44120238/94480620-902c0380-01a4-11eb-8ff8-534342176ff0.png)

![popup4](https://user-images.githubusercontent.com/44120238/94480629-94582100-01a4-11eb-92b1-5a0c016baaa5.png)

These are the two extra popups in this walkthrough. Also, this happens just once on install for both the options page and the popup page as expected.

**Comment by asalia-1** [comment]
I have created a pull request for this feature, all that is left to confirm is the content of the popups

**Comment by kalicki1** [comment]
Since we merged this branch, I think we should be all set to close this issue.
