### ISSUE TITLE
Syncing users' Domain List with online database

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#34]
We've decided to split issue #25 into two new issues since it discussed separate topics. Here's what @SebastianZimmeck mentioned about syncing whitelists in issue #25:

> But, maybe, if we are thinking more longterm, it is worth it to start with something more intricate that supports the syncing of the whitelists (Firebase?).

Let's use this issue to discuss possible options for syncing our users' whitelists as well as for uploading its implementation.

(cc'ing @davebaraka @rgoldstein01)

**Comment by SebastianZimmeck** [comment]
I will be creating a Firebase backend in the next week or so.

**Comment by kalicki1** [comment]
The recent commit here has all the changes I made when I was trying to implement Firebase earlier this week. I managed to get a simple Firebase connection going between our extension and my Cloud Firestore database using the prepackaged Google documentation functions. All of these calls and the Firebase configuration information should be stored in `firebase.js`. 

The biggest issue I ran into while trying to implement Firebase is importing the necessary JS through our HTML docs and background JS files, since extensions generally don't seem to support that. To resolve that, I changed the extension `background` page in our `manifest.json` from `"scripts": ["libs/psl.js-1.8.0/psl.min.js", "background.js"]` (as done in the current master branch), to `"page": "background.html"`. Then from within the new `background.html` page I call all the background and Firebase scripts I previously needed to run in the background.

I also started implementing Firebase authentication by adding a basic sign-in button to the Settings page that was meant to trigger Firebase's authentication feature, but I didn't spend enough time to make it work so I took the minimal code that was there out.

**Comment by kalicki1** [comment]
@rgoldstein01, this is what I was referring to in our meeting. No worries if you can't get to this, I know you are already fairly busy. Let me know if you have any questions if you do take a look however. This code is very much work in progress.

(cc'ing @SebastianZimmeck )

**Comment by SebastianZimmeck** [comment]
Thanks, @kalicki1. I have created a Firebase backend stub. You and @rgoldstein01 should have access.

**Comment by SebastianZimmeck** [comment]
@rgoldstein01, do you have time to do this? (It is OK if not.)

**Comment by kalicki1** [comment]
We are currently thinking that we can close this issue and open a new general purpose issue regarding restarting this online syncing issue given we have made so many changes since this issue was first opened. Let's come back to this sometime this week and decide what to do with it then.
