### ISSUE TITLE
Add copyright notice to each file and what its code is for

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#36]
@kalicki1, once we have a name, could you add the following copyright notice to each source file?

```
"""
[name] is licensed under the MIT License
Copyright (c) 2020 Kuba Alicki, David Baraka, Rafael Goldstein, Sebastian Zimmeck
privacy-tech-lab, https://privacy-tech-lab.github.io/
"""


"""
[filename]
================================================================================
[one sentence description]
"""
```

In fact, it would be even better if the description is in some format that allows to generate documentation from it. Maybe, [sphinx-js](https://pypi.org/project/sphinx-js/) (at least, for JS files, not sure whether there is any cross-language solution)? Generally, it would be nice if all comments, not just at the top of the files, were written in a format that can be parsed into documentation. E.g., per `sphinx-js`:

```
/**
 * Return the ratio of the inline text length of the links in an element to
 * the inline text length of the entire element.
 *
 * @param {Node} node - Types or not: either works.
 * @throws {PartyError|Hearty} Multiple types work fine.
 * @returns {Number} Types and descriptions are both supported.
 */
function linkDensity(node) {
    const length = node.flavors.get('paragraphish').inlineLength;
    const lengthWithoutLinks = inlineTextLength(node.element,
                                                element => element.tagName !== 'A');
    return (length - lengthWithoutLinks) / length;
}
```

So, if you have time, it would be good if you could reformat all comments accordingly.

(cc'ing @davebaraka and @rgoldstein01)

**Comment by kalicki1** [comment]
I pushed changes to all the comments in the JavaScript files we created according to the JSDoc format. Hopefully these new comments are formatted well enough for `sphinx-js` to parse. I have not tried rendering any documentation yet, so there might need to be some changes made to the comments here and there if any problems arise. 

As for our non-JS files, I'm wondering if we need to do the same kind of comment updates for our CSS and HTML documents. I'm thinking probably not for our HTML, but I'm not sure about the CSS docs we have. @SebastianZimmeck, let me know what you think we should do regarding these non-JS files, as well as what you think about the general formatting so far.

**Comment by SebastianZimmeck** [comment]
Great! My suggestion would be to use CSS comments as documented [here](https://www.w3schools.com/css/css_comments.asp) and HTML comments as documented [here](https://www.w3schools.com/html/html_comments.asp). I am not sure if there exists any tool to auto-generate documentation from CSS or HTML files. But that is OK.

Once you finalized those comments, feel free to open a PR.

**Comment by kalicki1** [comment]
Alright, I pushed the last of the comments for now. I will open a pull request and when we merge, I think we should be able to close this issue!

**Comment by SebastianZimmeck** [comment]
Sounds good!
