### ISSUE TITLE
Implement acknowledgment to user that opt out was successful

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#38]
If a user opts out, it would be nice to have some acknowledgment from the service that received the request that it was received and that it will be honored.

Also, if someone opts out and they are not from California and the service receiving that signal only does the opt out for California consumers, there needs to be some signal back to the browser extension explaining why the request is refused (and also not send it again). 

Overall, this is a pretty complex feature, whose implementation depends a lot on how the backend looks like, which is something that we do not know at this point.

This feature requires a communications channel, which is difficult to establish by just a browser extension. Some, backend synching may be necessary (issue #34).

(cc'ing @davebaraka and @rgoldstein01)

**Comment by SebastianZimmeck** [comment]
As just discussed, we do not necessarily need to do this for every type of opt out OptMeowt supports. We can just do it for the IAB, which provides for it in their specification, and our own header-based opt out functionality. Same for issue #47.

**Comment by SebastianZimmeck** [comment]
One technically difficult point here may be that there may not be a general API to read response headers (see e.g., a [related thread](https://stackoverflow.com/questions/220231/accessing-the-web-pages-http-headers-in-javascript)). I guess at the worst we can have our own server and redirects etc.

(This point is equally relevant for issue #47, which is the same issue as this one accept for a successful opt out.)

**Comment by kalicki1** [comment]
We discussed in our standards group to remove a direct response from our future specification, so we can close this issue for the time being. We can continue to discuss overlap regarding this issue in issue #47, though we will start to shift towards looking into using `.well-known` folders as a 'response,' as well as maintaining our own public company list of Do Not Sell responses.
