### ISSUE TITLE
Improve settings and options page

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#46]
As @kalicki1 suggested today, it may be worthwhile to add some more detail in terms of options and settings, e.g., explain how the extension actually works (via cookies and headers), what Do Not Sell is (e.g., that it is different from opting out from ads or tracking),  the law it is based on (CCPA, Nevada SB221, ...).

(cc'ing @rgoldstein01 and @davebaraka)

**Comment by SebastianZimmeck** [comment]
Still relevant, @kalicki1? If so, please fix and close.

**Comment by kalicki1** [comment]
Per our call today, we know we will be working on a landing page and extensive documentation for various Do Not Sell extension implementations. We can close this issue since it is being taken care of elsewhere.
