### ISSUE TITLE
Show the user when a recipient denies Do Not Sell

### ISSUE THREAD

**Issue by dmarti** [privacy-tech-lab/optmeowt-browser-extension#47]
In some cases, a business receiving a Do Not Sell can refuse it and provide an explanation.

> A request to opt-out need not be a verifiable consumer request. If a business, however, has a good-faith, reasonable, and documented belief that a request to opt-out is fraudulent, the business may deny the request. The business shall inform the requestor that it will not comply with the request and shall provide an explanation why it believes the request is fraudulent.

[Final Text of Regulations - Title 11. Law - Division 1. Attorney General - Chapter 20. California Consumer Privacy Act Regulations - oal-sub-final-text-of-regs.pdf](https://www.oag.ca.gov/sites/all/files/agweb/pdfs/privacy/oal-sub-final-text-of-regs.pdf)

In the event that this happens, make the user aware of the denial, and make the explanation available to the user.

**Comment by SebastianZimmeck** [comment]
Very good point, @dmarti. Your suggestion is essentially the flip side of issue #38, acknowledging that the request was received and will be honored. So, we will be implementing a communications channel that allows this feedback from company to user.

**Comment by SebastianZimmeck** [comment]
(cc'ing @davebaraka and @rgoldstein01)

**Comment by SebastianZimmeck** [comment]
As just discussed, we do not necessarily need to do this for every type of opt out OptMeowt supports. We can just do it for the IAB, which provides for it in their specification, and our own header-based opt out functionality. Same for issue #38.

**Comment by dmarti** [comment]
Another example of where a refusal may happen: "not a covered business"

**Comment by SebastianZimmeck** [comment]
@dmarti, do you mean because the CCPA is not applicable to a business (e.g., it does not have the required minimum number of users in California)?

**Comment by dmarti** [comment]
Yes. The IAB just has "does not apply to this user in this context" which is general.

https://github.com/InteractiveAdvertisingBureau/USPrivacy/blob/master/CCPA/USP%20API.md#requirements-for-us-privacy-user-signal-api

**Comment by SebastianZimmeck** [comment]
Got it!

**Comment by SebastianZimmeck** [comment]
One technically difficult point here may be that there may not be a general API to read response headers (see e.g., a [related thread](https://stackoverflow.com/questions/220231/accessing-the-web-pages-http-headers-in-javascript)). I guess at the worst we can have our own server and redirects etc.

(This point is equally relevant for issue #38 for a succesful opt out.)

**Comment by kalicki1** [comment]
Given that we are no longer discussing receiving Do Not Sell responses, we will open a new issue with regards to the possibility of handling 'responses' to show the user via `.well-known` folders.
