### ISSUE TITLE
Implement DAA opt out

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#50]
As discussed in issue #42, I believe the baseline functionality for our variation of the DAA CCPA opt-out tool is basically finalized. At this point we should focus on updating our list of 3rd party cookies with as many different versions as we can, so we can support opting out of as many services as we can.

This will also help with testing to ensure that our DAA opt-out functionality works as intended. The more cookies we can verify work as intended, the more certain we can be our extension will work for all future 3rd party cookie cases. 

@SebastianZimmeck, if you have time feel free to add cookies for services you find to our 3rd party cookie JSON file once I merge issue #42. I will do the same.

**Comment by kalicki1** [comment]
**Thought about saving URLs in our JSON as well as domains**
Another thought I had is that we could find specific URLs we know will work for our cookie-setting process. This would potentially replace the URL-guessing game I am doing at the moment. Right now the extension takes the given domain and adds `https://` to the front and `/` to the back as the path as a simple string operation. This has worked so far, so we might not need to add specific URLs, but it is just a thought in case we need to do so in the future.

**Comment by SebastianZimmeck** [comment]
> @SebastianZimmeck, if you have time feel free to add cookies for services you find to our 3rd party cookie JSON file once I merge issue #42. I will do the same.

Sounds good!

(cc'ing @rgoldstein01 and @davebaraka)

**Comment by kalicki1** [comment]
I spent today wrapping up our DAA tool 3rd party cookie collection and compiled it into a Google Doc I have [linked here](https://docs.google.com/document/d/1a-vfjqgyElhELenN-eyCtxV-w-FY4GMaFISP1-Nv2tk/edit?usp=sharing). 

The doc above contains all of the cookies that the DAA tool places, including those with generated values. I went back through the first half of the companies on the DAA tool list to update this document with all of the cookies they place, even if they don't seem to be of much value. 

My intention with this complete document is to have a record of all of the cookies the DAA tool placed in order to keep our future analyses clean and concise. If we want to make modifications to our final list (which will most likely be shorter), we can reference this original copy if we ever need to revisit a decision we make.

**Comment by SebastianZimmeck** [comment]
Great! @kalicki1, do you have some summary statistics?

- How many companies does the DAA tool currently have?
- For how many companies were you able to implement the opt out in OptMeowt?
- For how many companies does the opt out via OptMeowt work/not work?

Also, if there are companies for which it does not work, do you know the reaon?

**Comment by kalicki1** [comment]
### Stats
Yes, @SebastianZimmeck! Here are some statistics:
- The DAA tool currently has **62 companies** supported.
- Of the 62 companies listed, the DAA tool _failed_ for  **5/62 companies**. As a side note, I was able to scrape one cookie from the DAA tool for EMX, though evidently not all of them as the tool notified me the procedure failed. The tool also **does not specify the reason for failure**. The five are as follows:
1. AddThis
2. Choozle
3. EMX
4. Oracle Data Cloud
5. Semasio
- OptMeowt was able to place the cookies I collected (from the complete list) from the DAA tool for the remainder of the **57/62** companies. This number excludes EMX since it 'failed,' though it technically did place the one EMX cookie I found. In other words, you could say OptMeowt placed cookies for 58/62 companies (thought it might not be all of the ones required for an opt out). 

- The failure dialogs the DAA tool provide are fairly generic as well:
>Opt-out requests for 1 participating companies were not completed. This may be the result of a temporary technical issue. Select "Try Again" to request opt outs from those companies again. Click "Learn More" for additional help.

>We notice a certain level of response failures during our status check. Your browser settings, added extensions, or network settings may be interfering with the intended functionality of the opt out tool, potentially leading to opt out failure as the participating companies are unable to to respond to a request to drop an opt-out cookie on this browser.

I have not done any checks outside of placing cookies via OptMeowt and verifying they are the same cookies the DAA tool placed for all of its partner companies. The best we can say is if the cookies were placed by the DAA tool and I managed to find them, OptMeowt was then able to place them. I have not been able to verify with the DAA tool that it I am 'opted out' since there is no functionality for that. This is something the NAI tool seems to do, but as you mentioned the legal language around both are different. 

In the coming days I can begin to snoop around the sites provided by the DAA tool for any ways to verify I am opted out, though not all sites provide that option. If you have any more sound ideas for all of the companies @SebastianZimmeck , let me know.

**Comment by SebastianZimmeck** [comment]
Excellent results, @kalicki1!

**Comment by SebastianZimmeck** [comment]
I believe I came across a first party custom opt out cookie. When I go to https://www.thegreatcoursesplus.com/ccpa and click on `To opt out from the “sale” of personal information through interest-based / targeted advertising, please click OPT OUT HERE` the following cookie is placed for the domain www.thegreatcoursesplus.com.

@kalicki1, perhaps you can try out if you see the same result and use this cookie as one instance to test the first/third party custom cookie list (I think the list(s) should cover both first and third party custom cookies). 

<img width="708" alt="Screen Shot 2020-08-05 at 8 24 54 AM" src="https://user-images.githubusercontent.com/11034003/89412585-58996180-d6f5-11ea-813f-04678075493a.png">

**Comment by SebastianZimmeck** [comment]
One very important point here is that there may be identifiers in cookies that are used by ad networks participating in the DAA tool to know which users to opt out. So, it is not only the opt out cookies (which are determining whether a user is opted out or not) but also the identifier cookies that OptMeowt needs to place. In principle, as OptMeowt upon first install is visiting all the sites of the DAA participants, those identifier cookies should be placed just as normal. @kalicki1, if you could say a few words where we are standing on this at the moment.

**Comment by kalicki1** [comment]
At the moment, OptMeowt isn't technically visiting each of the member DAA sites @SebastianZimmeck. OptMeowt has special permission, I believe by virtue of being a browser extension, to place those 3rd party cookies we have collected. I would be hesitant to say that those identifier cookies you mentioned are placed by the sites when the main opt out cookies are placed. This can be functionality we add ourselves, though this might actually require automated browser control that the user will have to see, unlike the current 'hidden' implementation. 

With regards to my plans on this issue, I have a list of the cookies I collected saved to our private [Google doc](https://docs.google.com/document/d/1a-vfjqgyElhELenN-eyCtxV-w-FY4GMaFISP1-Nv2tk/edit?usp=sharing), though I have not uploaded the final list of all the cookies yet just due to the nature of the security regarding the identifier cookies stored there. I'm thinking that I might replace these hashes with blank values and then upload the entire list to the repo. As discussed last week **we can do some small scale testing** on whether sites with their own DAA equivalent opt out place similar identifier cookies, though this might be time intensive.  

**What we can do**
In general, it is a bit difficult to tell whether or not identifier cookies are necessary simply because we cannot tell what ad network servers respond to. In principle, the CCPA opt outs do not need identifiers, and should be discouraged, though we cannot be 100% sure what ad networks are doing at the moment. @SebastianZimmeck, we may have touched on this last week, but I see two possible solutions for this issue at the moment. Should I come up with a procedure for screening out these 'identifier' cookies, or cookies with hashed values, and remove them from our list on the principle that they are unnecessary according to the CCPA? Or should we follow a possibly more pragmatic, "better safe than sorry," approach and include them, either with the hashes that were generated for me or blank hashes? What are your thoughts on this?

**Comment by SebastianZimmeck** [comment]
> What are your thoughts on this?

From my perspective, for the time being, it is OK to not include any identifier cookies (i.e., only include the opt out cookies). There may be some alternative tests to try:

- Place the opt out cookies with OptMeowt and visit the [DAA CCPA site](https://optout.privacyrights.info/?c=1) to see whether it shows that you are opted out
- The same approach but with the normal [DAA Do Not Track site](https://optout.aboutads.info/?c=2&lang=EN) or [NAI site](https://optout.networkadvertising.org/?c=1) as they seem pretty similar to the DAA CCPA site
- Contact the participating ad network and ask whether we are opted out (which we can do as part of our study)
- Observe whether the network traffic is different or different ads are being served

Trying the first two is probably worthwhile trying. The other two are not straightforward and we can come back to those later (if the first two did not lead to anything)

**Comment by kalicki1** [comment]
Later today, I will double check that we have uploaded the correct cookies lists, upload them, and finalize this issue. That should be the remainder of the work necessary here.

**Comment by SebastianZimmeck** [comment]
One final outstanding issue is to upload the updated list of DAA cookies from the WPES paper. Once that is done, this issue can be closed.

**Comment by kalicki1** [comment]
I pushed the updated list from our WPES paper to the `cookies_3p.yaml` file we keep for our DAA cookies. This issue should be all set.
