### ISSUE TITLE
Revise language in UI, code, and code comments

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#55]
We should adjust the language, e.g., instead of "whitelist" use "included" or "No Do Not Sell signal sent." Maybe, there are other uses of language beyond the term "whitelist" that we should also adjust. So, let us look through all the UI language, code comments, etc. to revise.

**Comment by kalicki1** [comment]
As discussed earlier today, I will make some major changes to the Domain List as mentioned in issue #56. Along with this, @SebastianZimmeck and I discussed updating the language of the About page, which should include, amongst other changes: 

- A link to our [Landing Page](https://privacy-tech-lab.github.io/optmeowt/) ([GitHub link](https://github.com/privacy-tech-lab/optmeowt))
- A link to our extension in the Chrome Web Store
- A link to the [privacy-tech-lab](https://privacy-tech-lab.github.io/) site
- A link to our technical documentation 
- Contact details (Our emails, Wesleyan, privacy-tech-lab, etc.)
- A notification to check for extension updates

**Comment by SebastianZimmeck** [comment]
@kalicki1, this should be a quick one. Can you fix and close?

**Comment by kalicki1** [comment]
Since the language has already been updated (especially with regards to the domain list language), we can close this issue.
