### ISSUE TITLE
Restructure Domain, Custom, and DAA lists

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#58]
As discussed with @kalicki1, we want to restructure OptMeowt's lists: the Domain, DAA, Custom Lists. This is a fundamental issue and should be resolved as soon as possible. What I am describing here goes a bit beyond what we discussed, @kalicki1. 

1. Domain List

<img width="966" alt="Screen Shot 2020-08-08 at 11 29 08 AM" src="https://user-images.githubusercontent.com/11034003/89714112-67d51500-d96a-11ea-8f29-1536e120a242.png">

What is currently the Whitelist should be the Domain list. Every domain the user visits should be included in this list. The current alphabetical ordering is good. Hiding some of the domains may be useful, but is not necessary, especially, as long as we have a search field.

There should be a toggle, checkbox, or other UI element in the Domain List giving the user the option to allow a particular domain to sell the user's data. For example, use a column heading "Do Not Sell Active" or something similar and for every domain a toggle with green color or a checkbox with checkmark set. By default, for all domains the setting is set to "Do Not Sell Active." 

The setting for a domain should be mirrored in the popup. In other words, the popup should show the current domain setting exactly as it appears in the Domain List. Currently, the settings in the popup ("Send Do Not Sell Signal" is active) and the UI elements in the Whitelist (whitelisting is disabled) diverge. That is not great. It is not very clear to the user that these are actually just different sides of the same coin.

The Domain List is in local storage and, by default, does not need to be mirrored or synced to any JSON/YAML/other data file. However, there should be an option for the user to export the Domain List into a JSON/YAML/other data file (per below, as we already have).

<img width="384" alt="Screen Shot 2020-08-08 at 12 30 14 PM" src="https://user-images.githubusercontent.com/11034003/89715333-05ccdd80-d973-11ea-8831-d370afc8507d.png">

For the import, to keep it simple for the time being, we can just overwrite the Domain List with whatever domains and settings are in the imported list (i.e. we do not need to compare and merge the imported list with whatever currently is in the Domain list). We can just show a warning that the content of the Domain List will be overwritten when the user makes use of the import functionality. 

To keep it simple for the time being, we do not need to have any functionality that the user can add or remove items from the Domain List via the UI. They would need to go through the import/export functionality.

The current functionality for deleting a domain from the Domain List is good, however, not critical in my opinion. So, if it currently does not work, we can drop it.

The Domain List should be technology-agnostic (issue #56). 

2. DAA List

The DAA List is a JSON/YAML/other data list that contains the DAA cookie names and values (issue #50). Upon running OptMeowt for the first time the cookies for all entries in the DAA List are placed. In addition, the domains are added to the Domain List.

3. Custom List

The custom list can be dropped. This means the language below should be changed to "Send Do Not Sell signals based on the settings in your Domain List".

<img width="598" alt="Screen Shot 2020-08-08 at 12 42 52 PM" src="https://user-images.githubusercontent.com/11034003/89715614-d9b25c00-d974-11ea-8957-c8030e6a5606.png">

Ideally, this option would also be enabled automatically as soon as the user makes a change to the Domain List (maybe a proxy would be if there is at least one domain in the Domain List for which Do Not Sell is not active). Similarly, the corresponding popup indicator (issue #30) would need to be in sync as well.

(This is an omnibus issue and may need to be broken down further. I wanted to describe the functionality in context, though.)

**Comment by kalicki1** [comment]
This is a great overview of the big picture tasks we need to do. I opened quite a few new issues that break down the remaining tasks and I will be closing them out one by one as they get wrapped up. Since many changes needed are small, many of these updates should be completed quickly and closed out quickly. We can keep this open for the time being as a reference, though I think I will be shifting over to the newer issues to log the more technical aspects of the work I'm doing.

**Comment by kalicki1** [comment]
Given that most of the issues here are resolved or have been implemented in other issues, we can close this one. We can refer back to this issue in the future as need be.
