### ISSUE TITLE
Start OptMeowt directly upon install

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#59]
As it currently stands, from a CCPA legal standpoint the installation of OptMeowt is an affirmative act to express the preference of globally opting out of the sale of persona. information. So, we no longer need to have the separate step of enabling OptMeowt. We can just remove it.

**Comment by kalicki1** [comment]
I implemented this feature in issue #45 since it was a small technical detail. This issue should be all set.
