### ISSUE TITLE
Test mechanism for syncing Do Not Sell signals across technologies

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#62]
This is an extension of our 'technology agnostic' Do Not Sell approach we began to implement in issue #56 and #58. Ideally, we would have all Do Not Sell signals stop sending immediately when a user chooses to bypass sending Do Not Sell signals to a specific company, including headers, first party cookies, and third party opt out cookies as well. Hence, we will need to delete those opt out cookies when a user chooses to bypass sending DNS signals to a company. 

This can also go the other way, by replacing those deleted cookies if a user chooses to change their mind and opts out of their sale in the future again.

**Comment by kalicki1** [comment]
I added a first version draft of this functionality in a recent commit in issue #58. This function passes some simple tests I threw at it, but it will need to be fleshed out further here.

**Comment by SebastianZimmeck** [comment]
I think this code can be merged and test for Firefox but as @kalicki1 said, it may be worth to add a tag as the first Firefox version of the code (possibly, not a release version, but I am also fine with a release version).
