### ISSUE TITLE
Improve the popup window's Domain List UI elements

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#63]
Since working on updating our Domain List in issue #56, I noticed that the relationship between some aspects of the popup window UI elements is unclear. This issue will be to resolve these discrepancies. 

- [x] Create a 'box' around the domain name and the `Do Not Sell Enabled` text and toggle to visually link the two together.
- [x] Add a link to the Domain List from within this box. 
<del>- [ ] Create a 'three-way' toggle within the popup that allows the user to see when the `Enabled` mode is switched from `Enabled`, `Domain List`, and `Disabled`. </del>
- [x] Show third party domains similar to first party domain but smaller text and buttons

Generally, keep UI clean, simple, and with as little text as possible.

SZ: Edit based on our discussion yesterday

**Comment by kalicki1** [comment]
After rereading @SebastianZimmeck's comment about this on issue #58, I noticed he mentioned that issue #30 touched upon the changes I mentioned we add in this issue. I will keep this issue open as an ongoing list of technical changes that need to be made, as well as a place to spitball ideas on the UI changes we can make.

**Comment by kalicki1** [comment]
I have been working on how to update our popup window elements to reflect the changes we've made to the domain list and the changes we discussed about emphasizing the 1st party domain and its responses over the 3rd party connected domains. This idea relates to issue #68. 

I uploaded a folder of some mockups in brach #63, under the `ui-mockup/Popup designs/` folder linked [here](https://github.com/privacy-tech-lab/optmeowt-browser-extension/tree/issue-63/ui-mockup/Popup%20designs). I have a screenshot for what I think our popup could look like considering the above changes below (this is `5. Flat Final` from the uploaded folder): 

<img width="700" alt="Screen Shot 2020-08-18 at 3 41 11 PM" src="https://user-images.githubusercontent.com/60238705/90557920-4265b980-e169-11ea-91de-7d8d7f4e74c3.png">

The language can change of course, and `Customizable Domain List` is meant to link to the Domain List in the settings page.

What do you think about this design @SebastianZimmeck?

**Comment by kalicki1** [comment]
This issue should be all set at this point in time.

**Comment by kalicki1** [comment]
**Note on the above commit** 
I just uploaded the remaining bits of code I had began to write in order to incorporate some visual elements that reflect the Do Not Sell response status of a given site, according to the response headers OptMeowt receives from a request. Since we have decided we will drop support for response headers, these changes are commented out but left in the code in this issue as a reference.

**Comment by kalicki1** [comment]
Taking a secondary glance at the code, I realized a few things were not quite finalized the way they should have been, and I reopened the issue to make note of them and push those changes. The only thing left to do at this point is to link the `Do Not Sell Request: SENT` notification in the popup with the actual request headers. Because of this I will keep the issue open.

**Comment by SebastianZimmeck** [comment]
At the moment, "sent" is checked even though a signal was not sent. @kalicki1 will fix this and then close this issue.

**Comment by kalicki1** [comment]
I have been working on this issue for a while, though it is still not finalized yet. Here is what I am thinking we do at the moment: 

Currently the new UI for the popup is only in this branch and has not yet been merged into the main branch. What I'm thinking is that we merge the current changes, and focus this issue after the merge specifically into making the signals receipts work. What is left to do is much more substantive than I initially anticipated, since registering what requests are made with the popup takes some fundamental reworking of what our extension passes around in the background. I have a rough draft of this code saved locally, though it is not yet ready to be uploaded.

I recommend we merge this issue, continue forward with our other issues, then come back to this when the time opens up.

**Comment by SebastianZimmeck** [comment]
Sounds good, @kalicki1. Though, please try to resolve this issue fairly soon (after you have done #70?). Let's try to avoid having too many open issues. Otherwise, nobody knows anymore what they were about.
