### ISSUE TITLE
Add a Domain List `import` overwrite warning (UI)

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#64]
This is fairly self explanatory. The only work here will be finding an elegant way of displaying this warning to the user. This will be mostly UI work, since a regular alert will most likely work fine.

**Comment by SebastianZimmeck** [comment]
> since a regular alert will most likely work fine 

Agreed. Let's have as little text as possible in the popup and other pages.

**Comment by SebastianZimmeck** [comment]
@asalia-1, please finish this by our meeting next week.
