### ISSUE TITLE
Add visual indicator in extension symbol that Do Not Sell request was sent and accepted (UI)

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#68]
Currently, we are counting the number of requests sent to the first and third parties upon visiting a website (see below). That is OK. 

<img width="188" alt="Screen Shot 2020-08-15 at 11 05 13 AM" src="https://user-images.githubusercontent.com/11034003/90315198-88134f80-dee7-11ea-8c54-82c146cf50e0.png">

However, maybe we can do something like below to indicate that a Do Not Sell signal was sent (S) and accepted (A). Maybe, it is also better (and easier) to just show one box. First the box shows S and then switches to A (or a red box with R for rejected).

<img width="470" alt="Screen Shot 2020-08-15 at 11 12 47 AM" src="https://user-images.githubusercontent.com/11034003/90315344-ccebb600-dee8-11ea-8d8f-1ba5b0481b02.png">

It does not necessarily need to be exactly like this, but in some way we need to make clear to the user that there is actually something happening (and what). Our situation is different from an ad blocker for which it is clear that it does work because no ads are shown anymore. We need to find a different way to make intuitively clear what is happening.

**Comment by kalicki1** [comment]
I have actually been toying around with this idea yesterday and created a rough version that adds a 'glowing ring' around the OptMeowt extension logo that indicates whether a signals was accepted or not. My initial thought was that if we send a signal but no response is received or the signal is rejected, then the logo would have a red 'glow,' and if our signal is sent and an affirming response is received, then the logo will 'glow' green. This would be independent of the popup, as you mentioned @SebastianZimmeck. The rough mockup would look something like this:

<img width="350" alt="Screen Shot 2020-08-15 at 3 42 11 PM" src="https://user-images.githubusercontent.com/60238705/90320300-097dd880-df0e-11ea-83b7-df5d1c598a93.png">

This is a draft version I made quickly in our source code. I ran a simple Node server to get a mock response. 

The 'rejected' or 'no response' ring would look like this: 

<img width="256" alt="Screen Shot 2020-08-15 at 3 42 55 PM" src="https://user-images.githubusercontent.com/60238705/90320307-169ac780-df0e-11ea-8ca4-f85a77b031b1.png">

How do you feel about something like this @SebastianZimmeck? Maybe the red is too bold or visually intrusive, so I was thinking we could use a gray or yellow ring as an alternative. This is a separate issue, but I was also thinking ahead and was planning on making the whole icon gray out for a site that the user has turned off in their domain list.

**Comment by kalicki1** [comment]
I do like the idea of having a simple A or R with a green/red background colored badge though as well. Your mockups show that idea off well. The only thing is I'm not sure if we will be able to have two badges, one for `sent` and one for `accepted/rejected`, but I haven't looked into that yet.

**Comment by SebastianZimmeck** [comment]
I think the glowing ring is a great idea! I like it better than the rectangles. It is more subtle, and I would find that clear.

It would need to be complemented with some intuitive explanation in the popup (a red writing maybe also some encircled saying Do Not Sell not accepted or something like that).

**Comment by kalicki1** [comment]
Given we have decided to drop HTTP responses in our spec and the UI is implemented here, I will upload the local code I have on my machine and close this issue. Then we can open a new issue regarding changing the extension and publisher backends to work with `.well-known` folders instead of responses.

**Comment by kalicki1** [comment]
It looks like the implementation for this issue was taken care of in branch issue #63. We should be all set to close this out.
