### ISSUE TITLE
Add visualization in OptMeowt extension icon

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#77]
We would like to indicate to the user that OptMeowt is actually working and doing something. Perhaps an easy way, for the time being, could be to add a little green circle to the extension icon if a Do Not Sell signal has been sent. Counting the number of signals sent similar to an ad blocker showing a counter for the number of ads blocked could be an alternative. This feature is largely a usability feature to make clear to the user that something is happening. If we want, we can make it more sophisticated later on, e.g. with adding a visual for receiving responses or fetching `well-known` items. But at this point, it is not necessary.

**Comment by kalicki1** [comment]
For the time being, as you mentioned @SebastianZimmeck, I pushed some code that will change the default "no ring" OptMeowt icon to one with a "glowing green ring" when we send at least one Do Not Sell request to an active tab. This current implementation does not differentiate between between 1st party or 3rd party connections, just as long as at least one signal is sent, the icon turns green. As a side note, I also did not implement the "red glowing ring" though we do have the option to do so in the future.

**Comment by kalicki1** [comment]
I think I am satisfied with this implementation for now, and if we want to get fancier with what the green status represents we can do so at a later date. Let me know if you have any other thoughts @SebastianZimmeck, but otherwise I think we can merge and close this issue.

**Comment by SebastianZimmeck** [comment]
Sounds good! Feel free to close whenever you think it is good.
