### ISSUE TITLE
Publish OptMeowt in the Chrome Web Store

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#81]
I started the publication process in the Chrome Web Store. Here is the [prerelease version](https://github.com/privacy-tech-lab/optmeowt-browser-extension/releases/tag/v0.1-alpha) that I submitted to the Store as of your latest commit, @kalicki1. 

@kalicki1, can you provide some missing info on the [permissions](https://developer.chrome.com/extensions/declare_permissions) that we are using? Also, is it correct what I am writing below?

<img width="1160" alt="Screen Shot 2020-09-26 at 8 53 59 PM" src="https://user-images.githubusercontent.com/11034003/94353027-6c4cae80-003a-11eb-95ae-80c7ec9fd6f3.png">

- webRequest justification: HTTP requests are used to send Do Not Sell and Do Not Share signals to visited websites

- webRequestBlocking justification: <not sure, @kalicki1?> 

- storage justification: Storage is used to maintain a domain list that identifies to which sites a user wants to send Do Not Sell or Do Not Share signals

- activeTab justification: The active tab is used to identify whether the current site should receive a Do Not Sell or Do Not Share signal

- cookies justification: Cookie values are stored to identify whether a user opted out from the sale or sharing of personal information on a particular site 

- Host permission justification: <not sure, @kalicki1?>

Also, if you are aware that we are actually not using a permission, we should remove it.

**Comment by kalicki1** [comment]
Yes, it looks like what you wrote was spot on! The other two permissions you mentioned you weren't sure about are both necessary: 

1. We're using `webRequestBlocking` as an extension of `webRequest` because we need to be able to pause each request to ensure our Do Not Sell signals are actually attached to each request. 
2. The host permission is just what Google calls the `<all_urls>` URL pattern matching permission. This just tells the Chrome APIs what sites it is allowed to modify. This is necessary if we want to be able to send Do Not Sell signals to any site the user requests.

**Comment by SebastianZimmeck** [comment]
Excellent! Thanks, @kalicki1. I will update that info on the Chrome Web Store, and we are on our way ...

**Comment by kalicki1** [comment]
Sounds good, @SebastianZimmeck! I hope the host permission doesn't slow down the processing time, it looks like they say they review those extensions that use it more closely. I'm trying to look up a way to avoid using the `<all_urls>` URL pattern permission, but fundamentally the API we use to pause outgoing requests requires a URL pattern that isn't too easy to modify. These are the `webRequest.onBeforeSendHeaders` and `webRequest.onHeadersReceived` calls we make in `background.js` if you are wondering.

**Comment by SebastianZimmeck** [comment]
OK, that is good. I am not sure if there is a way around the host permission. If it does not get reviewed in time, we just can link to link to the unpackaged version of OptMeowt for the time being.

**Comment by SebastianZimmeck** [comment]
OK, I have not submitted yet. The review may take up to a [few weeks](https://developer.chrome.com/webstore/faq#faq-listing-08) (apparently because of the host permission). 

Here is some info Google showed me to avoid the host permission and speed up the review. I am leaving this issue open for the time being, and we can discuss tomorrow. Not sure if just the activeTab permission would work for us and whether it is worth trying to fix it.

> Because of the following issue, your extension may require an in-depth review:
> - Broad Host Permissions
> Instead of requesting broad host permissions, consider using the activeTab permission, or specify the sites that your extension needs access to. Both options are more secure than allowing full access to an indeterminate number of sites, and they may help minimize review times.

> The activeTab permission allows access to a tab in response to an explicit user gesture.

> {
> ...
> "permissions": ["activeTab"]
> }
> If your extension only needs to run on certain sites, simply specify those sites in the extension manifest:

> {
> ...
> "permissions": ["https://example.com/*"]
> }

**Comment by kalicki1** [comment]
I have been messing around with these permissions for a short while but it doesn't seem like there's an easy way to avoid using the host permission with the WebRequest API. I think my recommendation for now would be to submit our extension to the Chrome Web Store and have them review it as it stands right now, @SebastianZimmeck. It might be more hassle than its worth trying to find any other kind of workaround.

**Comment by SebastianZimmeck** [comment]
OK, sounds good. I submitted OptMeowt for review as is. Will keep you updated ...
