### ISSUE TITLE
Improve tutorial notifications

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#84]
@kalicki1 [mentioned](https://github.com/privacy-tech-lab/optmeowt-browser-extension/pull/82#pullrequestreview-497975801) two improvements for the tutorial notifications:

> Here are my thoughts on this issue right now, it should just be small details at this point:
> 
> I think we should maybe add a general popup in the center of the page when the options page opens up to say something like, "Hi! Welcome to OptMeowt, here's a quick tutorial." This will help ease the user into the tutorial. (Once we make a landing page, we could potentially have it link to a Thank You page on there instead, but that's an aside.)
> 
> If it's possible, maybe we could switch the last popup to point to the `Domain List` button in the sideways navbar instead of the dark mode switch, since that is an important feature. The only thing is I know implementing this might be tough since the site loads in multiple parts and it might be hard to grab the exact location of the link.
> 
> Besides those two things I think this should be fine to merge.

**Comment by SebastianZimmeck** [comment]
A few improvements we discussed:

- Upon install redirect to landing page (issue #90)
- Right-align text in notifications or display as block (as opposed to centered)
- Have a brief welcome in the first notification ("Hello there, so glad you are here!" or something like that)
- Have a "spotlight" on the current item the notification is pointing to. Otherwise, everything looks sort of inactive.

**Comment by SebastianZimmeck** [comment]
The green halo of the extension icon in the browser bar that @kalicki1 implemented looks really cool. Perhaps, there is a way that the notifications also explain (and point to the halo) saying that the green color means that a signal was sent. Not a hugely important issue but would be nice to explain somewhere (or maybe not, do a la Snap and let users find out).

**Comment by SebastianZimmeck** [comment]
A few improvement suggestions:

- Change from "Save your preferences and upload them using this section." to "Import and export your customized list of sites that should receive a signal."
- Change "Toggle this to change color theme of the extension" to "Toggle this switch to change the color theme of OptMeowt."
- Let's keep the green halo a bit mysterious and not explain it.
- After the last notification on the settings page closes the feeling is really anti-climatic. I am just left on the settings page and nothing is happening. Can there be some kind of fun popup maybe with confetti or something saying "Enjoy!" and disappear after 2 seconds or so?

**Comment by asalia-1** [comment]
I will add a notification before then tutorial along the lines of "Welcome to OptMeowt"  and a notification after the tutorial along the lines of "Enjoy using OptMeowt" to make it a bit more lively and work on adjusting the language as well. I will add buttons to the pop ups so it's clear how to close popups and move from one popup to the other

**Comment by SebastianZimmeck** [comment]
Sounds good!

**Comment by asalia-1** [comment]
![image (12)](https://user-images.githubusercontent.com/44120238/95781273-74902500-0c9b-11eb-87ba-12d68f9b010e.png)
![image (13)](https://user-images.githubusercontent.com/44120238/95781599-2a5b7380-0c9c-11eb-8417-a033782f98f3.png)
![image (10)](https://user-images.githubusercontent.com/44120238/95781288-7eb22380-0c9b-11eb-9b51-e4f8ebd1c16c.png)
![image (9)](https://user-images.githubusercontent.com/44120238/95781292-81147d80-0c9b-11eb-863e-8b7c89fb295a.png)
![image (8)](https://user-images.githubusercontent.com/44120238/95781299-82de4100-0c9b-11eb-8f1c-8452fd8481d0.png)

**Comment by asalia-1** [comment]
This is a basic outline of what mini tutorial looks like. Image on welcome modal is a bit off but I will fix that by end of day.

**Comment by SebastianZimmeck** [comment]
If you are asking "Would you like to have a quick walkthrough?", there should be an option "Not now." Otherwise, it is bit pointless to ask and not a great user experience.

Also, instead of "OptMeowt extension has been installed" I would prefer "OptMeowt has been installed".

**Comment by SebastianZimmeck** [comment]
@asalia-1, let's have this finished by tomorrow.

**Comment by asalia-1** [comment]
Sounds good

**Comment by asalia-1** [comment]
Created a pr to open options walkthrough on install and left-align pop-over content
