### ISSUE TITLE
Update readme as to Chrome Web Store link, files, folders, libraries, etc. used in this repo

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#86]
It seems to me the readme is a bit out of date in terms of the files, folders, libraries, etc. used in this repo. It would be good if you could update it, @kalicki1.

**Comment by SebastianZimmeck** [comment]
Maybe, put the install instruction at the beginning.

**Comment by SebastianZimmeck** [comment]
The readme should also include a prominent link to the [Chrome Web Store page of OptMeowt](https://chrome.google.com/webstore/detail/optmeowt/hdbnkdbhglahihjdbodmfefogcjbpgbo).

**Comment by SebastianZimmeck** [comment]
@asalia-1, this is a good issue for you to do. Let me know if you have any questions.

**Comment by SebastianZimmeck** [comment]
For example, what is the node server directory used for? Does anyone know? Maybe, it can be deleted.

**Comment by SebastianZimmeck** [comment]
Maybe, it also serves a purpose, in which case it should be listed and briefly described in the readme.

**Comment by asalia-1** [comment]
Understood, just by looking at it I am not entirely sure what it's purpose may have been. A wild guess is that it was @kalicki1 's attempt at implementing a mock server. In any case I will cross check with him to see if we need it or not

**Comment by asalia-1** [comment]
Updated ReadMe with a link to landing page and Chrome Web Store. I also removed unnecessary node server directory and updated directory list with new files.
