### ISSUE TITLE
Update Chrome Web Store Info

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#89]

**Comment by SebastianZimmeck** [comment]
As discussed today, we need a few promotional images (video is not necessary; not sure what the promo tiles are and whether we need them; definitely we want the five screenshots) for OptMeowt's site on the Chrome Web Store. Here are the specifications. 

<img width="603" alt="Screen Shot 2020-10-06 at 10 43 12 PM" src="https://user-images.githubusercontent.com/11034003/95281566-81d58b80-0825-11eb-89b8-e1ead9041f55.png">

Also, the store icon I uploaded is not really great. Maybe, just use the cat's head?

<img width="426" alt="Screen Shot 2020-10-06 at 10 46 16 PM" src="https://user-images.githubusercontent.com/11034003/95281735-dc6ee780-0825-11eb-9d98-f7b2969b8054.png">

Here is some [guidance by Google](https://developer.chrome.com/webstore/images) on the format and size of icons, screenshots, etc.

@asalia-1, feel free to upload the images here in the issue or on MS Teams. 

Also, you can find some inspiration from other extension's pages, for example, [DuckDuckGo's Privacy Essentials](https://chrome.google.com/webstore/detail/duckduckgo-privacy-essent/bkdgflcldnnnapblkhphbgpggdiikppg).

**Comment by SebastianZimmeck** [comment]
Because of the launch of GPC today, I would say, this is the most high priority issue on your plate at the moment, @asalia-1. 
So, if you work on something, try to make progress here.

**Comment by asalia-1** [comment]
![Component 1](https://user-images.githubusercontent.com/44120238/95347367-cba48d00-088a-11eb-89ee-75bc15c1ecf0.png)
![Component 2](https://user-images.githubusercontent.com/44120238/95347385-cfd0aa80-088a-11eb-913f-52fe2e409037.png)
![Component 3](https://user-images.githubusercontent.com/44120238/95347388-d3643180-088a-11eb-939a-e537facf277b.png)

**Comment by asalia-1** [comment]
Hi @SebastianZimmeck , these are some screenshots I prepared for the web store.

**Comment by asalia-1** [comment]
All screenshots have been set to appropriate size. With approval of content, I will go ahead to update screenshots and store icon on chrome web store. I will then proceed to work on promo tiles

**Comment by SebastianZimmeck** [comment]
Thanks, @abdallah. The icon is not quite aligned. Also, per the guidance from Google I mention above there should be some whitespace. I think I have to post the screenshots and other items because there is no good way to share the Chrome Web Store account without sharing my personal password. Please go ahead with the promo tiles. I will update everything later today after teaching.

**Comment by asalia-1** [comment]
I reviewed language on screenshots together with @kalicki1 and created a pr to upload those assets. I am collaborating with him on some ideas for what we can use for promo images as well

**Comment by asalia-1** [comment]
Options for promo images

 
Large Promo Tile:
![optmeowt-promo-440-1](https://user-images.githubusercontent.com/44120238/95400853-b99e0b00-08d9-11eb-8e92-09279fde52ba.png)

Small Promo Tile
![optmeowt-promo-440-2](https://user-images.githubusercontent.com/44120238/95400870-c4f13680-08d9-11eb-95a2-9cce49c020ff.png)

**Comment by asalia-1** [comment]
All assets have been uploaded in this [pull request ](https://github.com/privacy-tech-lab/optmeowt-browser-extension/pull/93)with appropriate requirements

**Comment by SebastianZimmeck** [comment]
Thanks, @asalia-1. I added two promo tiles and submitted everything for review. The instructions said no alpha, which your screenshots actually had. I still submitted. If it comes back, we have to fix it.
