### ISSUE TITLE
Redirect to landing page upon installation of the extension

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/optmeowt-browser-extension#90]
Similar as for DuckDuckGo Privacy Essentials redirect to a [site](https://duckduckgo.com/app?post=1&atb=v241-7) after installation. Either a dedicated site or just our normal landing page.

**Comment by SebastianZimmeck** [comment]
@asalia-1 feel free to close if that is all.

**Comment by asalia-1** [comment]
Made changes to redirect user to OptMeowt landing page on install for now. I will consider possibility of having dedicated page for this as well and open a new issue if need be.
