### ISSUE TITLE
Duplicate GlobalPrivacyControl Script Tags

### ISSUE THREAD

**Issue by dknopf** [privacy-tech-lab/optmeowt-browser-extension#95]
Not sure how serious this is/why it's happening, but whenever I inspect element on a site with optmeowt on, I always found dozens of instances of the script tag defining the GlobalPrivacyControl property. More instances of the tag are added as I watch, but after a few seconds they seem to stop being added. It happens on every site I visit. I'm on version 1.0.1 of the extension. 

![image](https://user-images.githubusercontent.com/7244624/95691338-70f19500-0bec-11eb-9fef-e9644d4b5166.png)

**Comment by SebastianZimmeck** [comment]
Good find. @kalicki1, do you know?

**Comment by kalicki1** [comment]
This shouldn't be the case anymore since I implemented the `chrome.webNavigation.onCommitted` call Dave recommended we use instead in issue #92.
